// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const isUsableSupabaseEnvValue = (value: unknown) =>
  typeof value === "string" && value.trim() !== "" && value.trim().toLowerCase() !== "undefined";
const SUPABASE_PUBLIC_KEY = isUsableSupabaseEnvValue(SUPABASE_PUBLISHABLE_KEY)
  ? SUPABASE_PUBLISHABLE_KEY
  : SUPABASE_ANON_KEY;
const SUPABASE_PUBLIC_KEY_NAME = isUsableSupabaseEnvValue(SUPABASE_PUBLISHABLE_KEY)
  ? "VITE_SUPABASE_PUBLISHABLE_KEY"
  : isUsableSupabaseEnvValue(SUPABASE_ANON_KEY)
    ? "VITE_SUPABASE_ANON_KEY"
    : "none";
const SUPABASE_FUNCTIONS_URL = isUsableSupabaseEnvValue(SUPABASE_URL)
  ? `${SUPABASE_URL.replace(/\/+$/, "")}/functions/v1`
  : undefined;

console.debug("[Supabase debug] client init", {
  supabaseUrl: SUPABASE_URL,
  functionsUrl: SUPABASE_FUNCTIONS_URL,
  hasPublishableKey: isUsableSupabaseEnvValue(SUPABASE_PUBLISHABLE_KEY),
  hasAnonKey: isUsableSupabaseEnvValue(SUPABASE_ANON_KEY),
  usingKeyName: SUPABASE_PUBLIC_KEY_NAME,
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLIC_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
